### ISSUE TITLE
Background Geolocation ($100 bounty)

### ISSUE THREAD

**Issue by etaiklein** [etaiklein/wandr#1]
# The Problem
The point of this app is that you can 'set and forget' an alarm that gets updated by your geolocation.
I'll need background geolocation to make this happen.

## Work so far

- [This library](https://github.com/mauron85/react-native-background-geolocation) seems to fit my needs. But feel free to use any that works.
- I've made an [issue]( https://github.com/mauron85/react-native-background-geolocation/issues/12#issuecomment-264374892) for them
- [My attempt](https://github.com/etaiklein/wandr/commit/777edd8e0bb80942a29a9735f7289c943ed99d30) at integrating the library.

## Other ideas

- Create a [custom](https://facebook.github.io/react-native/docs/native-modules-android.html) [module](https://facebook.github.io/react-native/docs/native-modules-ios.html). This will take more work (additional compensation TBD).

## Tasks for completion:
1. Geolocation updates while the app is suspended.
2. Alarm time changes based on geolocation while the app is suspended
3. It works on IOS and Android

## Notes
See https://github.com/etaiklein/wandr/blob/master/app/components/welcome/index.js#L41 for working foreground implementation

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/78/) http://coderbounty.com/issue/78

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/79/) http://coderbounty.com/issue/79

**Comment by coderbounty-cowboy** [comment]
![Coderbounty](http://www.coderbounty.com/get_bounty_image/79/) http://coderbounty.com/issue/79

**Comment by seanauriti** [comment]
I added $20, also going to need this soon.

**Comment by seanauriti** [comment]
http://www.coderbounty.com/issue/79/

**Comment by seanauriti** [comment]
Was it fixed?

**Comment by etaiklein** [comment]
It's not fixed but it doesn't look like it will be fixed so I'm planning on closing the bounty and looking at other avenues.

**Comment by seanauriti** [comment]
I may be using it in a project soon and will fix it.  If you can keep it open for another month or so I think I will get to it.

**Comment by seanauriti** [comment]
https://bidhype.com/?page=listing&id=19
